"""initial schema

Revision ID: 29342947d7d1
Revises: 
Create Date: 2026-02-25 08:54:06.324236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29342947d7d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('wells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wells_id'), 'wells', ['id'], unique=False)
    op.create_index(op.f('ix_wells_name'), 'wells', ['name'], unique=True)
    op.create_table('bit_nozzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('nozzle_count', sa.Integer(), nullable=True),
    sa.Column('nozzle_sizes', sa.JSON(), nullable=True),
    sa.Column('tfa', sa.Float(), nullable=True),
    sa.Column('bit_diameter', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bit_nozzles_id'), 'bit_nozzles', ['id'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_number', sa.Integer(), nullable=True),
    sa.Column('depth_md_start', sa.Float(), nullable=True),
    sa.Column('depth_md_end', sa.Float(), nullable=True),
    sa.Column('depth_tvd', sa.Float(), nullable=True),
    sa.Column('header_data', sa.JSON(), nullable=True),
    sa.Column('operations_log', sa.JSON(), nullable=True),
    sa.Column('drilling_params', sa.JSON(), nullable=True),
    sa.Column('mud_properties', sa.JSON(), nullable=True),
    sa.Column('mud_inventory', sa.JSON(), nullable=True),
    sa.Column('bha_data', sa.JSON(), nullable=True),
    sa.Column('gas_monitoring', sa.JSON(), nullable=True),
    sa.Column('npt_events', sa.JSON(), nullable=True),
    sa.Column('hsse_data', sa.JSON(), nullable=True),
    sa.Column('cost_summary', sa.JSON(), nullable=True),
    sa.Column('completion_data', sa.JSON(), nullable=True),
    sa.Column('termination_data', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reports_id'), 'daily_reports', ['id'], unique=False)
    op.create_table('drillstring_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('od', sa.Float(), nullable=True),
    sa.Column('id_inner', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('order_from_bit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drillstring_sections_id'), 'drillstring_sections', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('hydraulic_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('section_type', sa.String(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('od', sa.Float(), nullable=True),
    sa.Column('id_inner', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hydraulic_sections_id'), 'hydraulic_sections', ['id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('depth_md', sa.Float(), nullable=False),
    sa.Column('depth_tvd', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('formation', sa.String(), nullable=True),
    sa.Column('mud_weight', sa.Float(), nullable=True),
    sa.Column('inclination', sa.Float(), nullable=True),
    sa.Column('azimuth', sa.Float(), nullable=True),
    sa.Column('torque', sa.Float(), nullable=True),
    sa.Column('drag', sa.Float(), nullable=True),
    sa.Column('overpull', sa.Float(), nullable=True),
    sa.Column('string_weight', sa.Float(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_table('survey_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('md', sa.Float(), nullable=False),
    sa.Column('inclination', sa.Float(), nullable=False),
    sa.Column('azimuth', sa.Float(), nullable=False),
    sa.Column('tvd', sa.Float(), nullable=True),
    sa.Column('north', sa.Float(), nullable=True),
    sa.Column('east', sa.Float(), nullable=True),
    sa.Column('dls', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_stations_id'), 'survey_stations', ['id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('workflow_used', sa.JSON(), nullable=False),
    sa.Column('confidence_summary', sa.JSON(), nullable=True),
    sa.Column('overall_confidence', sa.String(), nullable=True),
    sa.Column('individual_analyses', sa.JSON(), nullable=True),
    sa.Column('final_synthesis', sa.JSON(), nullable=True),
    sa.Column('leader_agent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_table('casing_design_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('casing_od_in', sa.Float(), nullable=True),
    sa.Column('casing_weight_ppf', sa.Float(), nullable=True),
    sa.Column('tvd_ft', sa.Float(), nullable=True),
    sa.Column('selected_grade', sa.String(length=20), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casing_design_results_id'), 'casing_design_results', ['id'], unique=False)
    op.create_table('cementing_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('casing_od_in', sa.Float(), nullable=True),
    sa.Column('hole_id_in', sa.Float(), nullable=True),
    sa.Column('casing_shoe_md_ft', sa.Float(), nullable=True),
    sa.Column('cement_density_ppg', sa.Float(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cementing_results_id'), 'cementing_results', ['id'], unique=False)
    op.create_table('completion_design_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('casing_id_in', sa.Float(), nullable=True),
    sa.Column('formation_permeability_md', sa.Float(), nullable=True),
    sa.Column('depth_tvd_ft', sa.Float(), nullable=True),
    sa.Column('penetration_berea_in', sa.Float(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completion_design_results_id'), 'completion_design_results', ['id'], unique=False)
    op.create_table('hydraulic_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('flow_rate', sa.Float(), nullable=True),
    sa.Column('mud_weight', sa.Float(), nullable=True),
    sa.Column('pv', sa.Float(), nullable=True),
    sa.Column('yp', sa.Float(), nullable=True),
    sa.Column('rheology_model', sa.String(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('bit_hydraulics', sa.JSON(), nullable=True),
    sa.Column('surge_swab', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hydraulic_results_id'), 'hydraulic_results', ['id'], unique=False)
    op.create_table('kill_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('well_name', sa.String(), nullable=True),
    sa.Column('depth_md', sa.Float(), nullable=True),
    sa.Column('depth_tvd', sa.Float(), nullable=True),
    sa.Column('original_mud_weight', sa.Float(), nullable=True),
    sa.Column('casing_shoe_tvd', sa.Float(), nullable=True),
    sa.Column('casing_id', sa.Float(), nullable=True),
    sa.Column('dp_capacity', sa.Float(), nullable=True),
    sa.Column('annular_capacity', sa.Float(), nullable=True),
    sa.Column('sidpp', sa.Float(), nullable=True),
    sa.Column('sicp', sa.Float(), nullable=True),
    sa.Column('pit_gain', sa.Float(), nullable=True),
    sa.Column('scr_pressure', sa.Float(), nullable=True),
    sa.Column('scr_rate', sa.Float(), nullable=True),
    sa.Column('strokes_surface_to_bit', sa.Float(), nullable=True),
    sa.Column('strokes_bit_to_surface', sa.Float(), nullable=True),
    sa.Column('total_strokes', sa.Float(), nullable=True),
    sa.Column('lot_emw', sa.Float(), nullable=True),
    sa.Column('calculations', sa.JSON(), nullable=True),
    sa.Column('pressure_schedule', sa.JSON(), nullable=True),
    sa.Column('kill_method', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kill_sheets_id'), 'kill_sheets', ['id'], unique=False)
    op.create_table('packer_forces_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('tubing_od', sa.Float(), nullable=True),
    sa.Column('tubing_id', sa.Float(), nullable=True),
    sa.Column('tubing_weight', sa.Float(), nullable=True),
    sa.Column('packer_depth_tvd', sa.Float(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packer_forces_results_id'), 'packer_forces_results', ['id'], unique=False)
    op.create_table('parameter_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('depth_md', sa.Float(), nullable=True),
    sa.Column('depth_tvd', sa.Float(), nullable=True),
    sa.Column('inclination', sa.Float(), nullable=True),
    sa.Column('azimuth', sa.Float(), nullable=True),
    sa.Column('mud_weight', sa.Float(), nullable=True),
    sa.Column('viscosity_pv', sa.Float(), nullable=True),
    sa.Column('viscosity_yp', sa.Float(), nullable=True),
    sa.Column('temperature_out', sa.Float(), nullable=True),
    sa.Column('flow_rate', sa.Float(), nullable=True),
    sa.Column('spp', sa.Float(), nullable=True),
    sa.Column('operation_code', sa.String(), nullable=True),
    sa.Column('wob', sa.Float(), nullable=True),
    sa.Column('rpm', sa.Float(), nullable=True),
    sa.Column('rop', sa.Float(), nullable=True),
    sa.Column('torque', sa.Float(), nullable=True),
    sa.Column('hook_load', sa.Float(), nullable=True),
    sa.Column('overpull', sa.Float(), nullable=True),
    sa.Column('pit_gain', sa.Float(), nullable=True),
    sa.Column('sidpp', sa.Float(), nullable=True),
    sa.Column('sicp', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parameter_sets_id'), 'parameter_sets', ['id'], unique=False)
    op.create_table('rca_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('root_cause_category', sa.String(), nullable=True),
    sa.Column('root_cause_description', sa.Text(), nullable=True),
    sa.Column('five_whys', sa.JSON(), nullable=True),
    sa.Column('fishbone_factors', sa.JSON(), nullable=True),
    sa.Column('corrective_actions', sa.JSON(), nullable=True),
    sa.Column('prevention_actions', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rca_reports_id'), 'rca_reports', ['id'], unique=False)
    op.create_table('report_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('from_time', sa.Float(), nullable=True),
    sa.Column('to_time', sa.Float(), nullable=True),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.Column('iadc_code', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('depth_start', sa.Float(), nullable=True),
    sa.Column('depth_end', sa.Float(), nullable=True),
    sa.Column('is_npt', sa.Boolean(), nullable=True),
    sa.Column('npt_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['daily_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_operations_id'), 'report_operations', ['id'], unique=False)
    op.create_table('sand_control_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('d50_mm', sa.Float(), nullable=True),
    sa.Column('uniformity_coefficient', sa.Float(), nullable=True),
    sa.Column('ucs_psi', sa.Float(), nullable=True),
    sa.Column('interval_length', sa.Float(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sand_control_results_id'), 'sand_control_results', ['id'], unique=False)
    op.create_table('shot_efficiency_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('log_points_count', sa.Integer(), nullable=True),
    sa.Column('net_pay_intervals', sa.Integer(), nullable=True),
    sa.Column('total_net_pay_ft', sa.Float(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shot_efficiency_results_id'), 'shot_efficiency_results', ['id'], unique=False)
    op.create_table('stuck_pipe_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('mechanism', sa.String(), nullable=True),
    sa.Column('decision_tree_path', sa.JSON(), nullable=True),
    sa.Column('free_point_depth', sa.Float(), nullable=True),
    sa.Column('pipe_stretch_inches', sa.Float(), nullable=True),
    sa.Column('pull_force_lbs', sa.Float(), nullable=True),
    sa.Column('risk_matrix', sa.JSON(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stuck_pipe_analyses_id'), 'stuck_pipe_analyses', ['id'], unique=False)
    op.create_table('torque_drag_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('friction_cased', sa.Float(), nullable=True),
    sa.Column('friction_open', sa.Float(), nullable=True),
    sa.Column('wob', sa.Float(), nullable=True),
    sa.Column('rpm', sa.Float(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_torque_drag_results_id'), 'torque_drag_results', ['id'], unique=False)
    op.create_table('vibrations_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('wob_klb', sa.Float(), nullable=True),
    sa.Column('rpm', sa.Float(), nullable=True),
    sa.Column('bit_diameter_in', sa.Float(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vibrations_results_id'), 'vibrations_results', ['id'], unique=False)
    op.create_table('wellbore_cleanup_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('flow_rate', sa.Float(), nullable=True),
    sa.Column('mud_weight', sa.Float(), nullable=True),
    sa.Column('pv', sa.Float(), nullable=True),
    sa.Column('yp', sa.Float(), nullable=True),
    sa.Column('hole_id', sa.Float(), nullable=True),
    sa.Column('pipe_od', sa.Float(), nullable=True),
    sa.Column('inclination', sa.Float(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wellbore_cleanup_results_id'), 'wellbore_cleanup_results', ['id'], unique=False)
    op.create_table('workover_hydraulics_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('ct_od', sa.Float(), nullable=True),
    sa.Column('wall_thickness', sa.Float(), nullable=True),
    sa.Column('ct_length', sa.Float(), nullable=True),
    sa.Column('flow_rate', sa.Float(), nullable=True),
    sa.Column('mud_weight', sa.Float(), nullable=True),
    sa.Column('hole_id', sa.Float(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workover_hydraulics_results_id'), 'workover_hydraulics_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workover_hydraulics_results_id'), table_name='workover_hydraulics_results')
    op.drop_table('workover_hydraulics_results')
    op.drop_index(op.f('ix_wellbore_cleanup_results_id'), table_name='wellbore_cleanup_results')
    op.drop_table('wellbore_cleanup_results')
    op.drop_index(op.f('ix_vibrations_results_id'), table_name='vibrations_results')
    op.drop_table('vibrations_results')
    op.drop_index(op.f('ix_torque_drag_results_id'), table_name='torque_drag_results')
    op.drop_table('torque_drag_results')
    op.drop_index(op.f('ix_stuck_pipe_analyses_id'), table_name='stuck_pipe_analyses')
    op.drop_table('stuck_pipe_analyses')
    op.drop_index(op.f('ix_shot_efficiency_results_id'), table_name='shot_efficiency_results')
    op.drop_table('shot_efficiency_results')
    op.drop_index(op.f('ix_sand_control_results_id'), table_name='sand_control_results')
    op.drop_table('sand_control_results')
    op.drop_index(op.f('ix_report_operations_id'), table_name='report_operations')
    op.drop_table('report_operations')
    op.drop_index(op.f('ix_rca_reports_id'), table_name='rca_reports')
    op.drop_table('rca_reports')
    op.drop_index(op.f('ix_parameter_sets_id'), table_name='parameter_sets')
    op.drop_table('parameter_sets')
    op.drop_index(op.f('ix_packer_forces_results_id'), table_name='packer_forces_results')
    op.drop_table('packer_forces_results')
    op.drop_index(op.f('ix_kill_sheets_id'), table_name='kill_sheets')
    op.drop_table('kill_sheets')
    op.drop_index(op.f('ix_hydraulic_results_id'), table_name='hydraulic_results')
    op.drop_table('hydraulic_results')
    op.drop_index(op.f('ix_completion_design_results_id'), table_name='completion_design_results')
    op.drop_table('completion_design_results')
    op.drop_index(op.f('ix_cementing_results_id'), table_name='cementing_results')
    op.drop_table('cementing_results')
    op.drop_index(op.f('ix_casing_design_results_id'), table_name='casing_design_results')
    op.drop_table('casing_design_results')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_survey_stations_id'), table_name='survey_stations')
    op.drop_table('survey_stations')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_problems_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_hydraulic_sections_id'), table_name='hydraulic_sections')
    op.drop_table('hydraulic_sections')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_drillstring_sections_id'), table_name='drillstring_sections')
    op.drop_table('drillstring_sections')
    op.drop_index(op.f('ix_daily_reports_id'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_bit_nozzles_id'), table_name='bit_nozzles')
    op.drop_table('bit_nozzles')
    op.drop_index(op.f('ix_wells_name'), table_name='wells')
    op.drop_index(op.f('ix_wells_id'), table_name='wells')
    op.drop_table('wells')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
